gemini-image-editing:
    prompt: >
        Edit the person in the image to make them look more attractive and appealing.
gemini-costume-transfer:
    prompt: >
        Transfer the costume from the second image onto this slimmer person in the first image.
