gemini:
    prompt: >
        Combine the two images by transferring the costume from the second image onto the person in the first image. Ensure that the costume fits the body naturally and realistically.
        The final output must be highly detailed, accurately reflecting the intricate textures and features of the costume from the second image, while also preserving the body contours of the person in the first image beneath the fabric.
        Pay close attention to fabric draping, natural shadows, and how the costume conforms to the body shape. Maintain the original pose and camera perspective of the first image.
        Finally, adjust the lighting and color tones of the costume so that they blend seamlessly with the lighting conditions of the first image.
